# Generated by Django 3.2.8 on 2021-10-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCarDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UploadPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.ImageField(blank=True, upload_to='upload_car', verbose_name='Image Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
